name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (without "v" prefix, ex. 1.0.0)'
        default: '1.0.0'
      draft:
        description: 'Should new release be a draft?'
        type: boolean
        required: true
        default: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  create_release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      # 1) artifact (tgcall win-x86_64)
      - uses: actions/download-artifact@v4
        with:
          name: tgcall win-x86_64 (msvc)
          path: './tgcall win-x86_64 (msvc)'
      - run: |
          rm -rf 'tgcall-win-x86_64.zip'
          zip -j -r 'tgcall-win-x86_64.zip' './tgcall win-x86_64 (msvc)'
      # 2) artifact (tgcall macos-aarch64)
      - uses: actions/download-artifact@v4
        with:
          name: tgcall macos-aarch64
          path: './tgcall.app'
      - run: |
          rm -rf 'tgcall-macos-aarch64.zip'
          zip -j -r 'tgcall-macos-aarch64.zip' './tgcall.app'
      # 3) artifact (tgcall linux-x86_64)
      - uses: actions/download-artifact@v4
        with:
          name: tgcall linux-x86_64 (glibc)
          path: './tgcall linux-x86_64 glibc'
      - run: |
          rm -rf 'tgcall-linux-x86_64-glibc.zip'
          zip -j -r 'tgcall-linux-x86_64-glibc.zip' './tgcall linux-x86_64 glibc'
      # upload release
      - uses: ncipollo/release-action@v1
        with:
          commit: 'master'
          tag: 'v${{ inputs.tag }}'
          allowUpdates: true
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          draft: '${{ inputs.draft }}'
          name: 'tgcall.rs ${{ inputs.tag }}'
          removeArtifacts: true
          artifacts: '*.zip'